-- TRIGGER INSERT --
USE smarkio_portosinistro;
DELIMITER |
CREATE TRIGGER tg_api_in AFTER INSERT ON leads
FOR EACH ROW
BEGIN
    IF ((NEW.erro_api IS NOT NULL)
    AND (SELECT EXISTS (
        SELECT * FROM smarkio_portosinistro.api_count 
        WHERE date = NEW.lead_creation_day 
        AND menu = CASE WHEN (NEW.erro_api = '100') THEN 'Continuar'
            WHEN (NEW.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (NEW.erro_api = '102') THEN 'Processando'
            WHEN (NEW.erro_api = '201') THEN 'Criado'
            WHEN (NEW.erro_api = '203') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (NEW.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (NEW.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (NEW.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (NEW.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (NEW.erro_api = '302') THEN 'Encontrado'
            WHEN (NEW.erro_api = '303') THEN 'Veja Outro'
            WHEN (NEW.erro_api = '304') THEN 'Não Modificado'
            WHEN (NEW.erro_api = '305') THEN 'Use Proxy'
            WHEN (NEW.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (NEW.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (NEW.erro_api = '401') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (NEW.erro_api = '403') THEN 'Proibido'
            WHEN (NEW.erro_api = '404') THEN 'Não encontrado'
            WHEN (NEW.erro_api = '405') THEN 'Método não Permitido'
            WHEN (NEW.erro_api = '406') THEN 'Não aceito'
            WHEN (NEW.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (NEW.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (NEW.erro_api = '409') THEN 'Conflito'
            WHEN (NEW.erro_api = '410') THEN 'Perdido'
            WHEN (NEW.erro_api = '411') THEN 'Duração necessária'
            WHEN (NEW.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (NEW.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (NEW.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (NEW.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (NEW.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (NEW.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (NEW.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (NEW.erro_api = '501') THEN 'Não implementado'
            WHEN (NEW.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (NEW.erro_api = '503') THEN 'Servico indisponível'
            WHEN (NEW.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (NEW.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END
        AND api = CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END)=0))
          
    THEN INSERT INTO smarkio_portosinistro.api_count
    (date, menu, api)
    VALUES (NEW.lead_creation_day, CASE WHEN (NEW.erro_api = '100') THEN 'Continuar'
            WHEN (NEW.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (NEW.erro_api = '102') THEN 'Processando'
            WHEN (NEW.erro_api = '201') THEN 'Criado'
            WHEN (NEW.erro_api = '203') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (NEW.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (NEW.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (NEW.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (NEW.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (NEW.erro_api = '302') THEN 'Encontrado'
            WHEN (NEW.erro_api = '303') THEN 'Veja Outro'
            WHEN (NEW.erro_api = '304') THEN 'Não Modificado'
            WHEN (NEW.erro_api = '305') THEN 'Use Proxy'
            WHEN (NEW.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (NEW.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (NEW.erro_api = '401') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (NEW.erro_api = '403') THEN 'Proibido'
            WHEN (NEW.erro_api = '404') THEN 'Não encontrado'
            WHEN (NEW.erro_api = '405') THEN 'Método não Permitido'
            WHEN (NEW.erro_api = '406') THEN 'Não aceito'
            WHEN (NEW.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (NEW.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (NEW.erro_api = '409') THEN 'Conflito'
            WHEN (NEW.erro_api = '410') THEN 'Perdido'
            WHEN (NEW.erro_api = '411') THEN 'Duração necessária'
            WHEN (NEW.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (NEW.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (NEW.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (NEW.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (NEW.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (NEW.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (NEW.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (NEW.erro_api = '501') THEN 'Não implementado'
            WHEN (NEW.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (NEW.erro_api = '503') THEN 'Servico indisponível'
            WHEN (NEW.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (NEW.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END,
        CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END);
   END IF;

    IF (NEW.erro_api != '200') THEN 
        UPDATE smarkio_portosinistro.api_count
        SET total = total + 1
        WHERE date = NEW.lead_creation_day 
        AND menu = CASE WHEN (NEW.erro_api = '100') THEN 'Continuar'
            WHEN (NEW.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (NEW.erro_api = '102') THEN 'Processando'
            WHEN (NEW.erro_api = '201') THEN 'Criado'
            WHEN (NEW.erro_api = '203') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (NEW.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (NEW.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (NEW.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (NEW.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (NEW.erro_api = '302') THEN 'Encontrado'
            WHEN (NEW.erro_api = '303') THEN 'Veja Outro'
            WHEN (NEW.erro_api = '304') THEN 'Não Modificado'
            WHEN (NEW.erro_api = '305') THEN 'Use Proxy'
            WHEN (NEW.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (NEW.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (NEW.erro_api = '401') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (NEW.erro_api = '403') THEN 'Proibido'
            WHEN (NEW.erro_api = '404') THEN 'Não encontrado'
            WHEN (NEW.erro_api = '405') THEN 'Método não Permitido'
            WHEN (NEW.erro_api = '406') THEN 'Não aceito'
            WHEN (NEW.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (NEW.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (NEW.erro_api = '409') THEN 'Conflito'
            WHEN (NEW.erro_api = '410') THEN 'Perdido'
            WHEN (NEW.erro_api = '411') THEN 'Duração necessária'
            WHEN (NEW.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (NEW.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (NEW.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (NEW.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (NEW.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (NEW.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (NEW.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (NEW.erro_api = '501') THEN 'Não implementado'
            WHEN (NEW.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (NEW.erro_api = '503') THEN 'Servico indisponível'
            WHEN (NEW.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (NEW.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END
        AND api = CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END;
    END IF;	
END

-- TRIGGER UPDATE --
USE smarkio_portosinistro;
DELIMITER |
CREATE TRIGGER tg_api_up AFTER UPDATE ON leads
FOR EACH ROW
BEGIN
    IF ((NEW.erro_api IS NOT NULL)
    AND (SELECT EXISTS (
        SELECT * FROM smarkio_portosinistro.api_count 
        WHERE date = NEW.lead_creation_day 
        AND menu = CASE WHEN (NEW.erro_api = '100') THEN 'Continuar'
            WHEN (NEW.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (NEW.erro_api = '102') THEN 'Processando'
            WHEN (NEW.erro_api = '201') THEN 'Criado'
            WHEN (NEW.erro_api = '203') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (NEW.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (NEW.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (NEW.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (NEW.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (NEW.erro_api = '302') THEN 'Encontrado'
            WHEN (NEW.erro_api = '303') THEN 'Veja Outro'
            WHEN (NEW.erro_api = '304') THEN 'Não Modificado'
            WHEN (NEW.erro_api = '305') THEN 'Use Proxy'
            WHEN (NEW.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (NEW.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (NEW.erro_api = '401') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (NEW.erro_api = '403') THEN 'Proibido'
            WHEN (NEW.erro_api = '404') THEN 'Não encontrado'
            WHEN (NEW.erro_api = '405') THEN 'Método não Permitido'
            WHEN (NEW.erro_api = '406') THEN 'Não aceito'
            WHEN (NEW.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (NEW.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (NEW.erro_api = '409') THEN 'Conflito'
            WHEN (NEW.erro_api = '410') THEN 'Perdido'
            WHEN (NEW.erro_api = '411') THEN 'Duração necessária'
            WHEN (NEW.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (NEW.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (NEW.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (NEW.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (NEW.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (NEW.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (NEW.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (NEW.erro_api = '501') THEN 'Não implementado'
            WHEN (NEW.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (NEW.erro_api = '503') THEN 'Servico indisponível'
            WHEN (NEW.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (NEW.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END
        AND api = CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END)=0))
          
    THEN INSERT INTO smarkio_portosinistro.api_count
    (date, menu, api)
    VALUES (NEW.lead_creation_day, CASE WHEN (NEW.erro_api = '100') THEN 'Continuar'
            WHEN (NEW.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (NEW.erro_api = '102') THEN 'Processando'
            WHEN (NEW.erro_api = '201') THEN 'Criado'
            WHEN (NEW.erro_api = '203') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (NEW.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (NEW.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (NEW.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (NEW.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (NEW.erro_api = '302') THEN 'Encontrado'
            WHEN (NEW.erro_api = '303') THEN 'Veja Outro'
            WHEN (NEW.erro_api = '304') THEN 'Não Modificado'
            WHEN (NEW.erro_api = '305') THEN 'Use Proxy'
            WHEN (NEW.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (NEW.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (NEW.erro_api = '401') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (NEW.erro_api = '403') THEN 'Proibido'
            WHEN (NEW.erro_api = '404') THEN 'Não encontrado'
            WHEN (NEW.erro_api = '405') THEN 'Método não Permitido'
            WHEN (NEW.erro_api = '406') THEN 'Não aceito'
            WHEN (NEW.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (NEW.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (NEW.erro_api = '409') THEN 'Conflito'
            WHEN (NEW.erro_api = '410') THEN 'Perdido'
            WHEN (NEW.erro_api = '411') THEN 'Duração necessária'
            WHEN (NEW.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (NEW.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (NEW.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (NEW.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (NEW.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (NEW.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (NEW.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (NEW.erro_api = '501') THEN 'Não implementado'
            WHEN (NEW.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (NEW.erro_api = '503') THEN 'Servico indisponível'
            WHEN (NEW.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (NEW.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END,
        CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END);
   END IF;

    IF (NEW.erro_api != '200') THEN 
        UPDATE smarkio_portosinistro.api_count
        SET total = total + 1
        WHERE date = NEW.lead_creation_day 
        AND menu = CASE WHEN (NEW.erro_api = '100') THEN 'Continuar'
            WHEN (NEW.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (NEW.erro_api = '102') THEN 'Processando'
            WHEN (NEW.erro_api = '201') THEN 'Criado'
            WHEN (NEW.erro_api = '203') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (NEW.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (NEW.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (NEW.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (NEW.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (NEW.erro_api = '302') THEN 'Encontrado'
            WHEN (NEW.erro_api = '303') THEN 'Veja Outro'
            WHEN (NEW.erro_api = '304') THEN 'Não Modificado'
            WHEN (NEW.erro_api = '305') THEN 'Use Proxy'
            WHEN (NEW.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (NEW.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (NEW.erro_api = '401') THEN 'Não autorizado'
            WHEN (NEW.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (NEW.erro_api = '403') THEN 'Proibido'
            WHEN (NEW.erro_api = '404') THEN 'Não encontrado'
            WHEN (NEW.erro_api = '405') THEN 'Método não Permitido'
            WHEN (NEW.erro_api = '406') THEN 'Não aceito'
            WHEN (NEW.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (NEW.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (NEW.erro_api = '409') THEN 'Conflito'
            WHEN (NEW.erro_api = '410') THEN 'Perdido'
            WHEN (NEW.erro_api = '411') THEN 'Duração necessária'
            WHEN (NEW.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (NEW.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (NEW.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (NEW.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (NEW.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (NEW.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (NEW.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (NEW.erro_api = '501') THEN 'Não implementado'
            WHEN (NEW.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (NEW.erro_api = '503') THEN 'Servico indisponível'
            WHEN (NEW.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (NEW.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END
        AND api = CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END;
    END IF;	

    IF (OLD.erro_api != '200') THEN 
        UPDATE smarkio_portosinistro.api_count
        SET total = total - 1
        WHERE date = OLD.lead_creation_day 
        AND menu = CASE WHEN (OLD.erro_api = '100') THEN 'Continuar'
            WHEN (OLD.erro_api = '101') THEN 'Mudando Protocolos'
            WHEN (OLD.erro_api = '102') THEN 'Processando'
            WHEN (OLD.erro_api = '201') THEN 'Criado'
            WHEN (OLD.erro_api = '203') THEN 'Não autorizado'
            WHEN (OLD.erro_api = '204') THEN 'Nenhum conteúdo'
            WHEN (OLD.erro_api = '205') THEN 'Resetar conteúdo'
            WHEN (OLD.erro_api = '206') THEN 'Conteúdo Parcial'
            WHEN (OLD.erro_api = '300') THEN 'Múltipla Escolha'
            WHEN (OLD.erro_api = '301') THEN 'Movido Permanentemente'
            WHEN (OLD.erro_api = '302') THEN 'Encontrado'
            WHEN (OLD.erro_api = '303') THEN 'Veja Outro'
            WHEN (OLD.erro_api = '304') THEN 'Não Modificado'
            WHEN (OLD.erro_api = '305') THEN 'Use Proxy'
            WHEN (OLD.erro_api = '306') THEN 'Proxy Trocado'
            WHEN (OLD.erro_api = '400') THEN 'Solicitação Inválida'
            WHEN (OLD.erro_api = '401') THEN 'Não autorizado'
            WHEN (OLD.erro_api = '402') THEN 'Pagamento necessário'
            WHEN (OLD.erro_api = '403') THEN 'Proibido'
            WHEN (OLD.erro_api = '404') THEN 'Não encontrado'
            WHEN (OLD.erro_api = '405') THEN 'Método não Permitido'
            WHEN (OLD.erro_api = '406') THEN 'Não aceito'
            WHEN (OLD.erro_api = '407') THEN 'Autenticação de Proxy Necessária'
            WHEN (OLD.erro_api = '408') THEN 'Tempo de solicitação esgotado'
            WHEN (OLD.erro_api = '409') THEN 'Conflito'
            WHEN (OLD.erro_api = '410') THEN 'Perdido'
            WHEN (OLD.erro_api = '411') THEN 'Duração necessária'
            WHEN (OLD.erro_api = '412') THEN 'Falha de pré condição'
            WHEN (OLD.erro_api = '413') THEN 'Solicitação da entidade muito extensa'
            WHEN (OLD.erro_api = '414') THEN 'Solicitação de URL muito Longa'
            WHEN (OLD.erro_api = '415') THEN 'Tipo de mídia não suportado'
            WHEN (OLD.erro_api = '416') THEN 'Solicitação de faixa não satisfatório'
            WHEN (OLD.erro_api = '417') THEN 'Falha na expectativa'
            WHEN (OLD.erro_api = '500') THEN 'Erro do servidor Interno'
            WHEN (OLD.erro_api = '501') THEN 'Não implementado'
            WHEN (OLD.erro_api = '502') THEN 'Portal de entrada ruim'
            WHEN (OLD.erro_api = '503') THEN 'Servico indisponível'
            WHEN (OLD.erro_api = '504') THEN 'Tempo limite da Porta de Entrada'
            WHEN (OLD.erro_api = '505') THEN 'Versap HTTP não suportada'
            ELSE 'Erro não listado' END
        AND api = CASE WHEN (OLD.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (OLD.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (OLD.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (OLD.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (OLD.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (OLD.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (OLD.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END;
    END IF;	
END