-- TRIGGER INSERT --
USE smarkio_portosinistro;
DELIMITER |
CREATE TRIGGER tg_assunto_in AFTER INSERT ON leads
FOR EACH ROW
BEGIN
    IF (SELECT EXISTS (
        SELECT * FROM smarkio_portosinistro.assunto_count 
        WHERE date = NEW.lead_creation_day 
        AND assunto = CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END)=0)
          
    THEN INSERT INTO smarkio_portosinistro.assunto_count
    (date, assunto, menu, retencao)
    VALUES (NEW.lead_creation_day, CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END,
        CASE WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END,
        CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END);
   END IF;

    IF (NEW.id IS NOT NULL)  THEN     
        UPDATE smarkio_portosinistro.assunto_count
        SET interacao = interacao + 1
        WHERE date = NEW.lead_creation_day 
        AND assunto = CASE WHEN (NEW.menu_principal = 'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal = 'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal = 'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END;
    END IF;	

    IF (NEW.transbordo_efetivado IS NOT NULL) THEN 
        UPDATE smarkio_portosinistro.assunto_count
        SET transbordo = transbordo + 1
        WHERE date = NEW.lead_creation_day 
        AND assunto = CASE WHEN (NEW.menu_principal = 'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal = 'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal = 'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END;
    END IF;	
END

-- TRIGGER UPDATE --
USE smarkio_portosinistro;
DELIMITER |
CREATE TRIGGER tg_assunto_up AFTER UPDATE ON leads
FOR EACH ROW
BEGIN
    IF (SELECT EXISTS (
        SELECT * FROM smarkio_portosinistro.assunto_count 
        WHERE date = NEW.lead_creation_day 
        AND assunto = CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END)=0)
          
    THEN INSERT INTO smarkio_portosinistro.assunto_count
    (date, assunto, menu, retencao)
    VALUES (NEW.lead_creation_day, CASE WHEN (NEW.menu_principal =  'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal =  'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal =  'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END,
        CASE WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END,
        CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END);
    END IF;

    IF (NEW.id IS NOT NULL)  THEN     
        UPDATE smarkio_portosinistro.assunto_count
        SET interacao = interacao + 1
        WHERE date = NEW.lead_creation_day 
        AND assunto = CASE WHEN (NEW.menu_principal = 'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal = 'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal = 'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END;
    END IF;	

    IF (NEW.transbordo_efetivado IS NOT NULL) THEN 
        UPDATE smarkio_portosinistro.assunto_count
        SET transbordo = transbordo + 1
        WHERE date = NEW.lead_creation_day 
        AND assunto = CASE WHEN (NEW.menu_principal = 'Status do processo') THEN 'Status do processo'
            WHEN (NEW.menu_principal = 'Envio de documentos') THEN 'Envio de documentos'
            WHEN (NEW.menu_principal = 'Outros assuntos') THEN 'Outros assuntos'
            WHEN (NEW.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (NEW.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (NEW.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (NEW.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (NEW.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (NEW.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (NEW.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (NEW.susep IS NOT NULL) THEN 'Corretor'
            WHEN (NEW.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (NEW.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (NEW.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (NEW.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (NEW.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (NEW.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (NEW.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (NEW.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (NEW.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (NEW.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (NEW.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (NEW.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (NEW.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (NEW.confidence >= 0.6) THEN 'Resolvido'
            WHEN (NEW.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END;
    END IF;	

     IF (OLD.id IS NOT NULL)  THEN     
        UPDATE smarkio_portosinistro.assunto_count
        SET interacao = interacao - 1
        WHERE date = OLD.lead_creation_day 
        AND assunto = CASE WHEN (OLD.menu_principal = 'Status do processo') THEN 'Status do processo'
            WHEN (OLD.menu_principal = 'Envio de documentos') THEN 'Envio de documentos'
            WHEN (OLD.menu_principal = 'Outros assuntos') THEN 'Outros assuntos'
            WHEN (OLD.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (OLD.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (OLD.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (OLD.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (OLD.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (OLD.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (OLD.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (OLD.susep IS NOT NULL) THEN 'Corretor'
            WHEN (OLD.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (OLD.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (OLD.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (OLD.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (OLD.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (OLD.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (OLD.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (OLD.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (OLD.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (OLD.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (OLD.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (OLD.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (OLD.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (OLD.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (OLD.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (OLD.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (OLD.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (OLD.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (OLD.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (OLD.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (OLD.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (OLD.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (OLD.confidence >= 0.6) THEN 'Resolvido'
            WHEN (OLD.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END;
    END IF;	

    IF (OLD.transbordo_efetivado IS NOT NULL) THEN 
        UPDATE smarkio_portosinistro.assunto_count
        SET transbordo = transbordo - 1
        WHERE date = OLD.lead_creation_day 
        AND assunto = CASE WHEN (OLD.menu_principal = 'Status do processo') THEN 'Status do processo'
            WHEN (OLD.menu_principal = 'Envio de documentos') THEN 'Envio de documentos'
            WHEN (OLD.menu_principal = 'Outros assuntos') THEN 'Outros assuntos'
            WHEN (OLD.menu_principal = 'Consultar outro sinistro') THEN 'Consultar outro sinistro'
            WHEN (OLD.nao_logado = 'Acompanhar um sinistro') THEN 'Acompanhar um sinistro'
            WHEN (OLD.nao_logado = 'Comunicar um sinistro') THEN 'Comunicar um sinistro'
            WHEN (OLD.nao_logado = 'Outros assuntos') THEN 'Outros assuntos'
            ELSE '-' END
        AND menu = CASE
            WHEN (OLD.tipo_usuario = 'Segurado') THEN 'Segurado'
            WHEN (OLD.tipo_usuario = 'Terceiro') THEN 'Terceiro'
            WHEN (OLD.tipo_usuario = 'Corretor') THEN 'Corretor'
            WHEN (OLD.susep IS NOT NULL) THEN 'Corretor'
            WHEN (OLD.sinistro LIKE '531%') THEN 'Segurado'
            WHEN (OLD.sinistro LIKE '553%') THEN 'Terceiro'
            ELSE 'Logado sem susep' END
        AND retencao = CASE WHEN (OLD.transbordo_efetivado IS NOT NULL) THEN 'Transbordo'
            WHEN (OLD.sinistro_encerrado_com_indenizacao LIKE 'N%') THEN 'Não Resolvido'
            WHEN (OLD.sinistro_encerrado_com_indenizacao = 'Sim') THEN 'Resolvido'
            WHEN (OLD.sinistro_sem_indenizacao LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (OLD.sinistro_sem_indenizacao = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Valor da Franquia') THEN 'Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Agendar vistoria') THEN 'Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Outros assuntos') THEN 'Não Resolvido'
            WHEN (OLD.menu_perda_parcial = 'Voltar ao menu anterior') THEN 'Não Resolvido'
            WHEN (OLD.nao_validou_dados = 'Tentar novamente') THEN 'Não Resolvido'
            WHEN (OLD.nao_validou_dados = 'Voltar ao menu inicial') THEN 'Não Resolvido'
            WHEN (OLD.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.envio_documento = 'Enviar documentos') THEN 'Não Resolvido'
            WHEN (OLD.envio_documento = 'Voltar ao Menu Principal') THEN 'Não Resolvido'
            WHEN (OLD.envio_documento = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.doc_pendente LIKE 'N%') THEN 'Não Resolvido'
            WHEN (OLD.doc_pendente = 'Sim') THEN 'Resolvido'
            WHEN (OLD.gancho_documento = 'Enviar  documentos') THEN 'Não Resolvido'
            WHEN (OLD.atendimento IS NOT NULL) THEN'Resolvido'
            WHEN (OLD.gancho_encerramento = 'Sim') THEN 'Resolvido'
            WHEN (OLD.gancho_documento LIKE 'Encerrar%') THEN 'Resolvido'
            WHEN (OLD.gancho_pesquisa = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.gancho_transferencia LIKE 'Falar com um t%') THEN 'Não Resolvido'
            WHEN (OLD.gancho_transferencia = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.nao_validou_dados = 'Encerrar') THEN 'Resolvido'
            WHEN (OLD.duvida IS NOT NULL) THEN'Resolvido'
            WHEN (OLD.problema_pagamento = 'Sim') THEN 'Resolvido'
            WHEN (OLD.problema_pagamento LIKE 'N%') THEN 'Não Resolvido'
            WHEN (OLD.pesquisa_satisfacao IS NOT NULL) THEN 'Resolvido'
            WHEN (OLD.confidence >= 0.6) THEN 'Resolvido'
            WHEN (OLD.confidence < 0.6) THEN 'Resolvido'
            ELSE 'Abandono' END;
    END IF;	
END